### ISSUE TITLE
No Chrome installations found error

### ISSUE THREAD

**Issue by nipuna777** [Yuyz0112/icomoon-cli#17]
Thank you for creating and maintaing this package! 

I'm trying to use it to add some icons, but keep getting an error on `chrome-launcher`. 

OSX 10.15.3
Chrome 80.0.3987.149
icomoon-cli ^1.3.2

It looks like the package depends on `chromy` that depends on an older version of `chrome-launcher` causing this issue. 

The stack trace is as follows:
```
[icomoon-cli] Preparing...
[icomoon-cli] Started a new chrome instance, going to load icomoon.io.
{ Error
    at new LauncherError (/Users/nipuna/Development/escooterapp/node_modules/chrome-launcher/dist/utils.js:35:22)
    at new ChromeNotInstalledError (/Users/nipuna/Development/escooterapp/node_modules/chrome-launcher/dist/utils.js:66:9)
    at Launcher.<anonymous> (/Users/nipuna/Development/escooterapp/node_modules/chrome-launcher/dist/chrome-launcher.js:145:27)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/nipuna/Development/escooterapp/node_modules/chrome-launcher/dist/chrome-launcher.js:9:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  message: 'No Chrome installations found.',
  code: 'ERR_LAUNCHER_NOT_INSTALLED' }
```
Are there any known work-arounds for this?

I am thinking of forking the library and re-doing the commands with `puppeteer`. Any thoughts?

**Comment by Yuyz0112** [comment]
Hi @nipuna777 

Personally I choose chromy to avoid downloading the chromium again and again for many puppeteer based tools.

But if it was not working, I believe we can switch to puppeteer or just use the chrome-launcher with another CDP lib.

Not sure when to have time to do this, so PR is welcomed.

**Comment by nipuna777** [comment]
> Personally I choose chromy to avoid downloading the chromium again and again for many puppeteer based tools.

That's a good point. Do you have any library that you prefer? [chrome-remote-interface](https://github.com/cyrus-and/chrome-remote-interface) seems to be pretty popular. 

> Not sure when to have time to do this, so PR is welcomed.

I have a mostly working version based on Pupetter, but the 'names' don't get applied. The indexdb changes are made correctly, but they don't seem to change the name. I'll try to come up with a PR for this.

**Comment by nipuna777** [comment]
@Yuyz0112 I've created a PR for this here: https://github.com/Yuyz0112/icomoon-cli/pull/18

It is working locally for me with Puppeteer and the test cases pass. Let me know if any changes need to be done.
